clinica/clinica/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("profesional/", include("profesional.urls")),
    path("sede/", include("sede.urls")),
    
]


if settings.DEBUG:
     from django.conf.urls.static import static
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clinica/home/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import reverse_lazy

from home import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("about_me/", views.about_me, name="about_me"),
    path("search/", views.search, name="search"),
    path('avatar/load', views.avatar_load, name='avatar-load'),
    path("signup/", views.signup, name="user-signup"),
    path('register/profile/', views.user_profile, name='user-profile'),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='registration/change-password.html',
            success_url=reverse_lazy("home:password-change-done")
        ),
        name="password-change"
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/change-password-done.html'
        ),
        name="password-change-done"
    ),
]

clinica/profesional/urls.py
from django.urls import path

from profesional import views

app_name = "profesional"
urlpatterns = [
    path("profesionales/", views.ProfesionalListView.as_view(), name="profesional-list"),
    path("profesional/add/", views.ProfesionalCreateView.as_view(), name="profesional-add"),
    path("profesional/<int:pk>/detail/", views.ProfesionalDetailView.as_view(), name="profesional-detail"),
    path("profesional/<int:pk>/update/", views.ProfesionalUpdateView.as_view(), name="profesional-update"),
    path("profesional/<int:pk>/delete/", views.ProfesionalDeleteView.as_view(), name="profesional-delete"),
    path("comment/<int:pk>/add/", views.CommentCreateView.as_view(), name="comment-create"),
    path("comment/<int:pk>/delete/", views.CommentDeleteView.as_view(), name="comment-delete"),
]

clinica/profesional/models.py
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.db import models
from ckeditor.fields import RichTextField


class Profesional(models.Model):
    name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    email = models.EmailField()
    especialidad = models.CharField(max_length=40)
    tel= models.IntegerField()
    description = RichTextField(null=True, blank=True)
    image = models.ImageField(upload_to='profesional', null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    comments = models.ManyToManyField(
        User, through="Comment", related_name="comments_owned"
    )
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    class Meta:
        unique_together = (
            "name",
            "last_name",
            "especialidad",
            "tel",
        )
        ordering = ["-created_at"]

    def __str__(self):
        return f"Profesional: {self.name} {self.last_name} | especialidad: {self.especialidad}"
    

class Comment(models.Model):
    text = models.TextField(
        validators=[
            MinLengthValidator(10, "El comentario debe ser mayor de 10 caracteres")
        ]
    )
    profesional = models.ForeignKey(Profesional, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

clinica/profesional/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms

from profesional.models import Profesional

class ProfesionalForm(forms.ModelForm):
    name = forms.CharField(
        label="Nombre del Profesional",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "profesional-name",
                "placeholder": "Nombre de profesional",
                "required": "True",
            }
        ),
    )
    last_name = forms.CharField(
        label="Apellido del profesional",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "profesional-last-name",
                "placeholder": "Apellido del profesional",
                "required": "True",
            }
        ),
    )
    email = forms.EmailField(
        label="Email:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "profesional-email",
                "placeholder": "email",
                "required": "True",
            }
        ),
    )
    especialidad = forms.CharField(
        label="Especialidad:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "profesional-especialidad",
                "placeholder": "Especialidad",
                "required": "True",
            }
        ),
    )
    tel = forms.IntegerField(
        label="Telefono:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "profesional-tel",
                "placeholder": "Telefono",
                "required": "True",
            }
        ),
    )

    description = forms.CharField(
        label="Descripción:",
        required=False,
        widget=CKEditorWidget(),
    )

    image = forms.ImageField()

    class Meta:
        model = Profesional
        fields = ["name", "last_name","email","especialidad","tel","description", "image"]


class CommentForm(forms.Form):
    comment_text = forms.CharField(
        label="",
        required=False,
        max_length=500,
        min_length=10,
        strip=True,
        widget=forms.Textarea(
            attrs={
                "class": "comment-text",
                "placeholder": "Ingrese su comentario...",
                "required": "True",
                "max_length": 500,
                "min_length": 10,
                "rows": 2,
                "cols": 10,
                "style":"min-width: 100%",
            }
        ),
    )

clinica/profesional/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from profesional.forms import CommentForm
from profesional.forms import ProfesionalForm
from profesional.models import Comment
from profesional.models import Profesional


class ProfesionalListView(ListView):
    model = Profesional
    paginate_by = 3

class ProfesionalDetailView(DetailView):
    model = Profesional
    template_name = "profesional/profesional_detail.html"
    fields = ["name", "last_name","email", "especialidad","tel", "description", "image"]

    def get(self, request, pk):
        profesional = Profesional.objects.get(id=pk)
        comments = Comment.objects.filter(profesional=profesional).order_by("-updated_at")
        comment_form = CommentForm()
        context = {
            "profesional": profesional,
            "comments": comments,
            "comment_form": comment_form,
        }
        return render(request, self.template_name, context)

class ProfesionalCreateView(LoginRequiredMixin, CreateView):
    model = Profesional
    success_url = reverse_lazy("profesional:profesional-list")

    form_class = ProfesionalForm

    def form_valid(self, form):
        """Filter to avoid duplicate profesionales"""
        data = form.cleaned_data
        form.instance.owner = self.request.user
        actual_objects = Profesional.objects.filter(
            name=data["name"], last_name=data["last_name"], email=data["email"],
        ).count()
        if actual_objects:
            messages.error(
                self.request,
                f"El profesional {data['name']} - {data['last_name']} ya está creado",
            )
            form.add_error("name", ValidationError("Acción no válida"))
            return super().form_invalid(form)
        else:
            messages.success(
                self.request,
                f"Profesional {data['name']} {data['last_name']} creado exitosamente!",
            )
            return super().form_valid(form)
        
class ProfesionalUpdateView(LoginRequiredMixin, UpdateView):
    model = Profesional
    fields = ["name", "last_name","email", "especialidad","tel", "description", "image" ]

    def get_success_url(self):
        profesional_id = self.kwargs["pk"]
        return reverse_lazy("profesional:profesional-detail", kwargs={"pk": profesional_id})
    

class ProfesionalDeleteView(LoginRequiredMixin, DeleteView):
    model = Profesional
    success_url = reverse_lazy("profesional:profesional-list")

class CommentCreateView(LoginRequiredMixin, CreateView):
    def post(self, request, pk):
        profesional = get_object_or_404(Profesional, id=pk)
        comment = Comment(
            text=request.POST["comment_text"], owner=request.user, profesional=profesional
        )
        comment.save()
        return redirect(reverse("profesional:profesional-detail", kwargs={"pk": pk}))
    
class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment

    def get_success_url(self):
        profesional = self.object.profesional
        return reverse("profesional:profesional-detail", kwargs={"pk": profesional.id})

clinica/profesional/templates/profesional/comment_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Comentario delete
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/home.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>Eliminar Comentario</h1>
                    <span class="subheading">Creado por: {{ comment.owner.first_name }} {{ comment.owner.last_name }}</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}

<h1>Estás seguro de eliminar el siguiente Comentario?</h1>
<p>{{ comment.text }}</p>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'profesional:profesional-detail' comment.profesional.id %}" >Cancelar</a>
</form>

{% endblock %}

clinica/profesional/templates/profesional/profesional_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Profesional delete
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/medicos.png')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ profesional.name }}</h1>
                    <span class="subheading">Eliminar Profesional</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}

<h1>Estás seguro de eliminar el Profesional: {{ profesional.name }} {{profesional.last_name}}?</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'profesional:profesional-list' %}" >Cancelar</a>
</form>

{% endblock %}

clinica/profesional/templates/profesional/profesional_detail.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Profesional detail
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/medicos.png')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ profesional.name }}</h1>
                    <h1>{{ profesional.last_name }}</h1>
                    <span class="subheading">Detalles del Profesional</span>
                </div>
            </div>
        </div>
        <a class="button_custom" href="{% url 'profesional:profesional-add' %}">Crear nuevo Profesional</a>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}
<!-- Post preview-->
<div class="post-preview">
    <h3 class="post-subtitle">Especialidad: {{ profesional.especialidad }}</h3>
    <h6 class="post-subtitle">Telefono: {{ profesional.tel }}</h6>
    <h6 class="post-subtitle">Email: {{ profesional.email }}</h6>
    <p class="post-meta">
        Creado por
        <span style="color: #0b4956;" href="">{{ profesional.owner.username }}</span>
        ( {{ course.created_at }} )
        <br>
        Última fecha de actualización ( {{ profesional.updated_at }} )
    </p>

    <!-- Image -->
    {% if profesional.image %}
        <div style="text-align: center;">
            <img height="250px" src="{{ profesional.image.url }}">
        </div>
    {% endif %}

    <!-- Description -->
    <p class="card-text ">{{ profesional.description|safe }}</p> <!-- ckeditor-->

    <!-- Update-Delete link only for the owner -->
    {% if user == profesional.owner or user.is_superuser %}
        <p style="text-align: center">
            <a href="{% url 'profesional:profesional-update' profesional.id %}">
                <i class="fa fa-pencil" style="color: #1c1c91;"></i> Editar Profesional
            </a>
            &ensp; | &ensp;
            <a href="{% url 'profesional:profesional-delete' profesional.id %}">
                <i class="fa fa-trash" style="color: #881a1a;"></i> Eliminar Profesional
            </a>
        </p>
    {% endif %}
    
    <!-- Divider-->
    <hr class="my-4" />

    <!-- Comment creation -->
    <form method="POST" action="{% url 'profesional:comment-create' profesional.id %}">
        {% csrf_token %}
        {{ comment_form }}
    <input type="submit" value="Publicar comentario">
    </form>
    {% if not comments %}
        <p></p>
    {% endif %}

    <!-- Comments list -->
    {% for comment in comments %}
        <p> {{ comment.text }}
            ({{ comment.owner.username }} | {{ comment.updated_at }})
            {% if user == comment.owner or user.is_superuser %}
            <a href="{% url 'profesional:comment-delete' comment.id %}"><i class="fa fa-trash" style="color: #881a1a;"></i></a>
            {% endif %}
        </p>
    {% endfor %}
</div>
{% endblock %}

clinica/profesional/templates/profesional/profesional_form.html
{% extends "home/index.html" %}
{% load static %}

<!-- ckeditor-->
{% block extrahead %}
<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
{{ block.super }}
{% endblock %}
<!-- ckeditor-->

{% block my_blog_title %}
Profesional Create-Update
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/medicos.png')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h2>Formulario para guardar/editar profesional</h2>
                    <span class="subheading">INFO SALUD</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
    <div>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }} <!-- ckeditor-->
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Guardar Profesional" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

clinica/profesional/templates/profesional/profesional_list.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Profesional list
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/medicos.png')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>Profesionales</h1>
                    <span class="subheading">INFO SALUD</span>
                </div>
            </div>
        </div>
        <a class="button_custom" href="{% url 'profesional:profesional-add' %}">Crear nuevo Profesional</a>
    </div>
</header>

{% endblock %}



{% block my_blog_content %}
    
    {% for profesional in profesional_list %}
       
        <!-- Post preview-->
        <div class="post-preview">
            <a href="{% url 'profesional:profesional-detail' profesional.id %}">
                <h2 class="post-title">Profesional: {{ profesional.name }} {{profesional.last_name}}</h2>
                <h3 class="post-subtitle">Especialidad: {{ profesional.especialidad }}</h3>
            </a>
            <p class="post-meta">
                Creado por
                <span style="color: #181543;" href="">{{ profesional.owner.username }}</span>
                ( {{ profesional.created_at }} )
            </p>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
    {% endfor %}
{% endblock %}