clinica/clinica/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("profesional/", include("profesional.urls")),
    path("sede/", include("sede.urls")),
    
]


if settings.DEBUG:
     from django.conf.urls.static import static
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clinica/home/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import reverse_lazy

from home import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("about_me/", views.about_me, name="about_me"),
    path("search/", views.search, name="search"),
    path('avatar/load', views.avatar_load, name='avatar-load'),
    path("signup/", views.signup, name="user-signup"),
    path('register/profile/', views.user_profile, name='user-profile'),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='registration/change-password.html',
            success_url=reverse_lazy("home:password-change-done")
        ),
        name="password-change"
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/change-password-done.html'
        ),
        name="password-change-done"
    ),
]

clinica/sede/urls.py
from django.urls import path

from sede import views

app_name = "sede"
urlpatterns = [
    path("sedes", views.sedes, name="sede-list"),
    path("sede/add", views.create_sede, name="sede-add"),
]

clinica/sede/models.py
from django.db import models

class Sede(models.Model):
    name = models.CharField(max_length=40)
    cod = models.IntegerField()
    tel= models.IntegerField()
    dir= models.CharField(max_length=40)

    def __str__(self):
        return f"Sede: {self.name} | codigo: {self.cod} | direccion: {self.dir}"
    

clinica/sede/forms.py
from django import forms


class SedeForm(forms.Form):
    name = forms.CharField(
        label="Nombre de la Sede",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "sede-name",
                "placeholder": "Nombre de la sede",
                "required": "True",
            }
        ),
    )
    cod = forms.IntegerField(
        label="Código de la Sede",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "sede-cod",
                "placeholder": "Código",
                "required": "True",
            }
        ),
    )
    dir = forms.CharField(
        label="Direccion:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "sede-dir",
                "placeholder": "Direccion",
                "required": "True",
            }
        ),
    )
    
    tel = forms.IntegerField(
        label="Telefono:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "sede-tel",
                "placeholder": "Telefono",
                "required": "True",
            }
        ),
    )

clinica/sede/views.py
from django.shortcuts import render
from django.contrib import messages

from sede.models import Sede
from sede.forms import SedeForm


def get_sedes(request):
    sedes = Sede.objects.all()
    return sedes


def create_sede(request):
    if request.method == "POST":
        sede_form = SedeForm(request.POST)
        if sede_form.is_valid():
            data = sede_form.cleaned_data
            actual_objects = Sede.objects.filter(
                name=data["name"],
                cod=data["cod"],
            ).count()
            print("actual_objects", actual_objects)
            if actual_objects:
                messages.error(
                    request,
                    f"La sede {data['name']} codigo: {data['cod']} ya está creada",
                )
            else:
                sede = Sede(
                    name=data["name"],
                    cod=data["cod"],
                    tel=data["tel"],
                    dir=data["dir"],
                )
                sede.save()
                messages.success(
                    request,
                    f"Sede {data['name']} codigo: {data['cod']} creada exitosamente!",
                )

            return render(
                request=request,
                context={"sedes": get_sedes(request)},
                template_name="sede/sede_list.html",
            )

    sede_form = SedeForm(request.POST)
    context_dict = {"form": sede_form}
    return render(
        request=request,
        context=context_dict,
        template_name="sede/sede_form.html",
    )


def sedes(request):
    sedes = Sede.objects.all()

    context_dict = {"sedes": sedes}

    return render(
        request=request,
        context=context_dict,
        template_name="sede/sede_list.html",
    )

clinica/sede/templates/sede/sede_form.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Sede
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('../../static/home/assets/img/ubicacion.png')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h2>Formulario para guardar una nueva Sede</h2>
                    <span class="subheading"> INFO SALUD </span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Guardar Sede" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

clinica/sede/templates/sede/sede_list.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Sede
{% endblock %}

{% block my_blog_header %}
    <header class="masthead" style="background-image: url('../../static/home/assets/img/ubicacion.png')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-15 col-lg-16 col-xl-14">
                    <div class="site-heading">
                        <h1>Sedes</h1>
                        <span class="subheading"> Podes encontrar nuestras sucursales: </span>
                    </div>
                </div>
            </div>
            {% if user.is_superuser %}
            <a class="button_custom" href="{% url 'sede:sede-add' %}">Crear nueva Sede</a>
            {% endif %}
        </div>
    </header>
{% endblock %}

{% block my_blog_content %}
    {% for sede in sedes %}
        <!-- Post preview-->
        <div class="post-preview">
            <h2 class="post-title">{{ sede.name }}</h2>
            <h3 class="post-subtitle">Direccion: {{ sede.dir }}</h3>
            <h3 class="post-subtitle">Telefono: {{ sede.tel }}</h3>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
    {% endfor %}
{% endblock %}